Added CRUD functions for customer and baggage
maknoon/airdb pull request #22
Opened 2017-11-06 23:25 UTC by katieli16

2017-11-07 00:04 UTC, maknoon requested changes
Looks good so far, added some comments

2017-11-07 00:04 UTC, maknoon commented on airplane.py
> +@app.route('/customer')
@katieli16 it would be good to create endpoints that can test the db functions like this and make sure that they are working before going forward

2017-11-07 00:04 UTC, maknoon commented on airplane.py
> +    return 'ADDED NEW CUSTOMER %s' % cust_name
should return the newly created customer ID here so the customer can use it as their reference login number later.

2017-11-07 00:04 UTC, maknoon commented on airplanedb.py
> +        db = MySQLdb.connect(host=self.host,
spacing should be 4 spaces = 1 tab

2017-11-07 00:04 UTC, maknoon commented on airplanedb.py
> +             print("Add Customer Success")
should return the customer ID here so as to give user a reference login number that they can use in the future

2017-11-07 00:05 UTC, maknoon commented on airplanedb.py
> +    def add_frequent_flier(self, cust_ID, miles):
we should have an update_frequent_flier function for every time the customer has logged more miles in their FF account?

2017-11-07 01:04 UTC, jefftwin commented on airplanedb.py
> +    def add_baggage(self, bag_ID, cust_ID, bag_weight):
baggage_ID is auto_incremented, so we dont have to pass this in to insert into table.

2017-11-07 01:05 UTC, jefftwin commented on airplanedb.py
> +                                 VALUES('%s','%s','%s','%s')""" % (cust_name, cust_age,
C_AGE should be an INT

2017-11-07 01:09 UTC, jefftwin commented on airplanedb.py
> +                          VALUES('%s', '%s')""" % (cust_ID, miles)
C_ID is int

2017-11-07 01:09 UTC, jefftwin commented on airplanedb.py
> +        add_baggage_query = """INSERT INTO BAGGAGE(B_ID,C_ID,B_WEIGHT)
C_ID is INT

2017-11-12 18:07 UTC, katieli16 commented on airplane.py
> +    return 'ADDED NEW CUSTOMER %s' % cust_name
Okay

2017-11-12 18:07 UTC, katieli16 commented on airplanedb.py
> +        db = MySQLdb.connect(host=self.host,
Oops, okay

2017-11-12 18:14 UTC, katieli16 commented on airplane.py
> +    return 'ADDED NEW CUSTOMER %s' % cust_name
I just realized that add/insert customer doesn't have a C_ID field? is that supposed to be a parameter or does it get created automatically?

2017-11-12 20:26 UTC, maknoon commented on airplane.py
> +    return 'ADDED NEW CUSTOMER %s' % cust_name
i believe `C_ID` is [auto-incremented as a primary key](https://github.com/maknoon/airdb/blob/master/airplanedb.py#L41), so when you insert a new tuple it will be automatically added to the table as a new entry!

2017-11-13 01:19 UTC, katieli16 commented on airplane.py
> +    return 'ADDED NEW CUSTOMER %s' % cust_name
Oh that's interesting. Is there a way to reference the newly created C_ID to return it? Just call C_ID?

2017-11-13 01:34 UTC, katieli16 commented on airplanedb.py
> +    def add_baggage(self, bag_ID, cust_ID, bag_weight):
Ok

2017-11-13 01:34 UTC, katieli16 commented on airplanedb.py
> +        add_baggage_query = """INSERT INTO BAGGAGE(B_ID,C_ID,B_WEIGHT)
Ok

2017-11-13 01:34 UTC, katieli16 commented on airplanedb.py
> +                                 VALUES('%s','%s','%s','%s')""" % (cust_name, cust_age,
Ok

2017-11-13 01:35 UTC, katieli16 commented on airplanedb.py
> +    def add_frequent_flier(self, cust_ID, miles):
Added

2017-11-13 01:35 UTC, katieli16 commented on airplanedb.py
> +                          VALUES('%s', '%s')""" % (cust_ID, miles)
Ok

2017-11-13 01:58 UTC, maknoon commented on airplane.py
> +    return 'ADDED NEW CUSTOMER %s' % cust_name
yes, there is a way to grab the C_ID using a property of `cursor` that you can add to the db function for inserting a new customer, something like
```
inserted = 0
try:
            # code for successful insert, db.commit() etc
            inserted = cursor.lastrowid
except: 
            # code for unsuccessful insert, db.rollback() etc
db.close()
return inserted
```

2017-11-13 02:03 UTC, maknoon requested changes

2017-11-13 02:03 UTC, maknoon commented on air
> +#!~/usr/bin/python
What is this file? Should probably remove it ;)

2017-11-13 02:03 UTC, maknoon commented on airplane.py
> +    if session.get('type') == 'user':
I think you accidentally copied in code from my branch! Should remove this code so it won't cause merge conflicts

2017-11-13 05:38 UTC, katieli16 commented on airplane.py
> +    if session.get('type') == 'user':
Ok done

2017-11-13 11:02 UTC, maknoon commented
Changes made before merge:
- removed a file that was accidentally commited to repo
- added fixes for `add_customer`, `add_frequent_flier` & tested endpoints
- took out `miles` when creating a frequent flier because it is always going to be 0 in the beginning
- added `get_customer` in db module
- commented out broken code for updating ff & customer  

Things from the #6 that still need to be fixed / addressed: 
- updates won't work as of right now, will make a note to fix that later 
- need to add delete for baggage 💣 
- ~~create a view for customer where it will show their flight, frequentflier status & baggage information if either of those are applicable~~ this could be in a diff task

2017-11-13 11:02 UTC, maknoon approved these changes

2017-11-13 11:03 UTC, merged

2017-11-13 11:04 UTC, maknoon commented
Unlinking this from #6 since that task was only partially completed in this PR (still need to do updates and deletes)