Implement CRUD functions for FLIGHT & ITINERARY
maknoon/airdb pull request #28
Opened 2017-11-14 01:23 UTC by katieli16

Please test insert and update for ITINERARY and FLIGHT because I don't think the Primary Keys are incrementing properly.

For example, if I try to add multiple itineraries for a customer, the id will be stuck at 0.

2017-11-15 03:55 UTC, maknoon commented
cc: @katieli16 

- Tested inserting itineraries, was working for me.
- The reason why updating itineraries was failing was because `id` is a built-in Python library function / property of objects, so you have to name the variable something different when you grab it from the query parameters (see [this line](https://github.com/maknoon/airdb/pull/28/commits/7a1f21b155bb00d6235cbdbce015a192330f3ee1#diff-e0b1b2c1fe73f519f15f25a3425b53e3L126)). Note also [here](https://github.com/maknoon/airdb/pull/28/commits/7a1f21b155bb00d6235cbdbce015a192330f3ee1#diff-f4fe62010a26202792961fa2d2642abdL672) that when writing a SQL query the attribute/field that you are specifying should not be in quotes.
- The reason why inserting flights was failing was because of a typo in the SQL query 😉 
- The reason why updating flights was failing was the same reason why updating itineraries was failing

2017-11-15 04:28 UTC, maknoon requested changes
Looks good so far! I made two commits to this PR that fix the more trivial insertion / update errors for FLIGHT & ITINERARY but left some comments for places where a different implementation will be needed for the respective functionalities to work.

2017-11-15 04:28 UTC, maknoon commented on airplanedb.py
> +        update_ff_query = """UPDATE FREQUENT_FLIER
this won't work because you are actually only inserting the value of miles into the string, but not actually adding it to the `FF_MILES` field of that tuple. in order to add miles, you would need to get the value of `FF_MILES` first, then add it to that value and update the tuple with the new sum

2017-11-15 04:28 UTC, maknoon commented on airplanedb.py
> +                           SET %s = '%s'
this is a good idea! but what about integer values in itinerary? the SQL query will fail because you would be trying to insert a string value into an integer-typed field. a way to fix this is to parse the command first in the endpoint at `airplane.py` and wrap the new_value inside single quotes if it is a string value, otherwise just send it as a str(int)

2017-11-15 04:28 UTC, maknoon commented on airplanedb.py
> +        update_flight_query = """UPDATE FLIGHT
see my comment about the same problem in `update_itinerary`

2017-11-16 00:44 UTC, katieli16 commented on airplanedb.py
> +        update_ff_query = """UPDATE FREQUENT_FLIER
fixed

2017-11-16 01:01 UTC, katieli16 commented on airplanedb.py
> +                           SET %s = '%s'
fixed

2017-11-16 01:07 UTC, katieli16 commented on airplanedb.py
> +        update_flight_query = """UPDATE FLIGHT
fixed

2017-11-16 03:32 UTC, maknoon commented
I see that a lot of code is being deleted in the files, is this right? Can @jefftwin confirm
@maknoon  Fixed everything

2017-11-16 09:22 UTC, jefftwin approved these changes

2017-11-16 09:24 UTC, jefftwin commented
@maknoon @katieli16 @galenhwang  going to go ahead and merge this into dev. please update ur branches

2017-11-16 09:24 UTC, merged