Some UI & RESTful Endpoint Refactoring
maknoon/airdb pull request #37
Opened 2017-11-16 07:59 UTC by maknoon

**related issues**: #30  
**changes**:  
- in `airplane.py`:  
  - refactored `/customer`, `/ff`, `/airport`, `/gate`, `/schedule`, `/flight`, `/itinerary`  
  - added some behavior for an admin view to be rendered via Jinja templating  
  - added helper function for wrapping some values from `PATCH` requests  
- in `airplanedb.py`:  
  - fixed a bunch of things  
  - renamed all returned JSON props to proper snake_case format
- in `templates/db.html`:  
  - implemented an example for how the admin UI can be rendered from a JSON object passed into `render_template()`  
  <img width="710" alt="screen shot 2017-11-15 at 11 57 42 pm" src="https://user-images.githubusercontent.com/5428281/32880239-c97c1fd0-ca61-11e7-823c-8e6cb11752ff.png">  

  - implemented a similar example for the user UI  
  <img width="653" alt="screen shot 2017-11-16 at 3 11 39 am" src="https://user-images.githubusercontent.com/5428281/32888487-4374f5f4-ca7c-11e7-99bf-baa89544658f.png">  

- other:
  - removed redundant chunk of documentation from `README`  

**how to test**: use a REST client as [documented](https://github.com/maknoon/airdb/wiki/Using-a-REST-Client-to-test-our-API) in the wiki. try logging in as a `user` or an `admin` (use `/logout` to logout)

2017-11-16 17:52 UTC, jefftwin approved these changes

2017-11-16 18:13 UTC, jefftwin requested changes

2017-11-16 18:13 UTC, jefftwin commented on airplanedb.py
> +                    'airport_id': airport[0],
@maknoon  does this implementation give the desired return? When I tested this on my branch, cursor.fetchone() returns a non-iteratable object so saying for airport in airports for cursor.fetchone() returns a corrupt json object

`else:
    airports = cursor.fetchone()

for airport in airports:`

2017-11-16 18:23 UTC, jefftwin requested changes

2017-11-16 18:23 UTC, jefftwin commented on airplane.py
> +            res_body = json.dumps(airport_json, indent=4, separators=(',', ': '))
hmmmm i think we should just json.dump the return object from airdb.get_airport. this is return corrupt json object

2017-11-16 18:44 UTC, maknoon commented on airplanedb.py
> +                    'airport_id': airport[0],
You're right; `json.dumps` won't work with how I am constructing the JSON object for `res_body` in the `/airport` router function. It's not a corrupt JSON object; rather that my function is taking values at indices of a string that is generated by `json.dumps`. ref. [json.dumps in Python](https://docs.python.org/2/library/json.html#json.dumps)

2017-11-16 18:45 UTC, jefftwin approved these changes

2017-11-16 18:46 UTC, maknoon commented on airplane.py
> +            res_body = json.dumps(airport_json, indent=4, separators=(',', ': '))
even better would be to just return what the db gives us! 😉

2017-11-16 20:46 UTC, katieli16 approved these changes
Also fixed the commented-out FF update

2017-11-17 00:10 UTC, galenhwang approved these changes

2017-11-17 00:11 UTC, merged