Refactored CRUD functions for AIRCRAFT, EMPLOYEE, and WORKSON
maknoon/airdb pull request #38
Opened 2017-11-16 09:56 UTC by galenhwang

2017-11-16 10:14 UTC, jefftwin requested changes
remember to add return comment and also have print statements when fail so we can check the log for exact failures. 

MAJOR ERRORS: check the get Aircraft function. the cursor.fetchone() doesn't work with json.dumps while cursor.fetchall(). This leads me to think you didn't full test each path. Please test each path and make sure everything works O=

2017-11-16 10:14 UTC, jefftwin commented on airplanedb.py
> +
After changing from jsonify to json.dump, this implementation for 

> cursor.fetchone()

doesnt work anymore. please look at the updated getAirport implementation

2017-11-16 10:14 UTC, jefftwin commented on airplanedb.py
> +
print out error with
`print(data)`
here too

2017-11-16 10:14 UTC, jefftwin commented on airplanedb.py
> +        delete_aircraft_query = """DELETE FROM AIRCRAFT WHERE AC_ID = %d""" % (int (ac_id))
not sure if the space in
`int (ac_id)`
would cause an error. delete the space

2017-11-16 10:14 UTC, jefftwin commented on airplanedb.py
> +            'ID': str(cursor.lastrowid),
is employeeID supposed to be string? should be int so leave it as an int in the json object

2017-11-16 10:14 UTC, jefftwin commented on airplanedb.py
> +#   description: delete a workson relation instance from table WORKSON
return comment

2017-11-17 01:16 UTC, maknoon requested changes
Looking good so far, please use `snake_case` for naming JSON object properties!

2017-11-17 01:16 UTC, maknoon commented on airplane.py
> +@app.route('/gate/delete')
You can remove this function; it is already implemented [here](https://github.com/maknoon/airdb/blob/dev_connie/airplane.py#L260)

2017-11-17 01:16 UTC, maknoon commented on airplane.py
> +@app.route('/aircraft/new')
Refactor `/aircraft/new`, `/aircraft/get`, `/aircraft/update` & `/aircraft/delete` into one endpoint `/aircraft`, see [this example](https://github.com/maknoon/airdb/blob/dev_connie/airplane.py#L211) for how to do it

2017-11-17 01:16 UTC, maknoon commented on airplane.py
> +@app.route('/employee/new')
please do the same RESTful refactoring here. see comment for refactoring `/aircraft`

2017-11-17 01:16 UTC, maknoon commented on airplane.py
> +@app.route('/schedule/getForItinerary')
This function can be removed; it is already included [here](https://github.com/maknoon/airdb/blob/dev_connie/airplane.py#L274)

2017-11-17 01:16 UTC, maknoon commented on airplane.py
> +@app.route('/workson/new')
please do the same RESTful refactoring here. see comment for refactoring `/aircraft`

2017-11-17 01:16 UTC, maknoon commented on airplane.py
> +@app.route('/schedule/add')
Can remove this function; it is already being implemented [here](https://github.com/maknoon/airdb/blob/dev_connie/airplane.py#L269)

2017-11-17 01:16 UTC, maknoon commented on airplane.py
> +@app.route('/schedule/delete')
Can remove this function; it is already being implemented [here](https://github.com/maknoon/airdb/blob/dev_connie/airplane.py#L269)

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +                'ID': cursor.lastrowid,
all JSON object props should be in `snake_case`
e.g. `Airport ID` -> `airport_id`
`Date Created` -> `date_created`
`Number of Economy` -> `num_economy`

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +                        'ID': aircraft[0],
use `snake_case`

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +                    'ID': aircrafts[0],
use `snake_case`

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +                'ID': aircraft[0],
use `snake_case`

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +            'ID': cursor.lastrowid,
use `snake_case`

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +                    'ID': e
use `snake_case`

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +                    'ID': f
use `snake_case`

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +            'ID': e_id
use `snake_case`

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +            'E_ID': e_id,
use `snake_case`
`E_ID` & `F_ID` should be `employee_id` & `flight_id`, respectively

2017-11-17 01:16 UTC, maknoon commented on airplanedb.py
> +            'E_ID': e_id,
use `snake_case`

2017-11-17 01:31 UTC, katieli16 requested changes
Can you write a get_works_on function that returns the entire works_on table?

2017-11-17 04:13 UTC, maknoon commented
~~@galenhwang can you delete `.DS_Store` from your PR (`git rm .DS_Store`) and add it to the `.gitignore` please~~ nvm I did it, just pull from this branch

2017-11-17 04:19 UTC, maknoon approved these changes

2017-11-17 06:09 UTC, jefftwin approved these changes

2017-11-17 06:09 UTC, merged